### ISSUE TITLE
 Button only rarely appears. Possibility to configure a HA domain or a normal toolbar button?

### ISSUE THREAD

**Issue by snetsplit** [warwickofthegh/Browser-Extension-Home-Assistant-Quick-Restart#4]
Home Assistant in Firefox seems to be hit or miss. Sometimes I get the button but quite often not, is there a Firefox setting that could be messing me up?

Would it be possible to specify my HA domain and use that for detection? Alternatively could a toolbar button be provided?

It's really handy when it does work!

**Comment by snetsplit** [comment]
I did some debugging on the initial issue.

(typeof hassConnection != "undefined")  in the console window on a HA returns true

I enabled extension logging on Firefox but I can't seem to find any logs with the text HA RESTART BROWSER EXT

My hunch is the JS code is never getting injected to test for the hassConnection object, because Firefox is not triggering the extension.

I'm using version 93.0 (64-bit) on Arch if that makes any difference.

**Comment by warwickbuilds** [comment]
Hi, I just fired up Firefox on Windows (v107) and installed the plugin and it was working fine.

vary rarely I notice its grey, but a quick F5 and it's enabled again. Are you seeing it consistently disabled?

**Comment by snetsplit** [comment]
Well since the time I submitted the bug I'm 107 firefox as well. It seems something changed so reloading does bring the button. When I submitted the bug, it didn't. Don't know if it was a local config issue or what. 

Thanks writing this though. It's very useful!
