### ISSUE TITLE
does this not work anymore ? 

### ISSUE THREAD

**Issue by rhgiter** [warwickofthegh/Browser-Extension-Home-Assistant-Quick-Restart#5]
does this not work anymore ? 
![image](https://user-images.githubusercontent.com/61065752/183256215-c6f94e08-0d1f-4aa4-9de7-4f374638c6bc.png)

**Comment by Shogun1978** [comment]
Doesn't work for me any longer also.

**Comment by warwickbuilds** [comment]
Hi, I'm running Chrome 107 and use it daily still myself without issue

what are you experiencing? just it being greyed out

**Comment by warwickbuilds** [comment]
Other users have reported all is working ok, closing due to age
