### ISSUE TITLE
FF addon not working anymore?

### ISSUE THREAD

**Issue by Cr4z33** [warwickofthegh/Browser-Extension-Home-Assistant-Quick-Restart#6]
Since latest stable update of Home Assistant it looks like your extension is not working anymore.

The addon spinning wheels keep turning forever and no restart is applied until I manually SSH and run `ha core restart`. 😕

**Comment by warwickbuilds** [comment]
1 star, bit harsh 😐

Honestly, the add-on does what it needs to do, so I haven't needed to update in years, though I personally still use daily (in Chrome though) - let me stoke the fox fire and give it a test. Generally closing and opening a new tabs makes it work again, but this seems to be a rare occurance.

**Comment by warwickbuilds** [comment]
Just tested in Firefox and it worked ok, if you perform a restart using HA UI does it successfully complete?

![image](https://github.com/warwickofthegh/Browser-Extension-Home-Assistant-Quick-Restart/assets/12653520/6a24cc0e-bb6f-4c82-a2ad-a313822387dd)

**Comment by Cr4z33** [comment]
> 1 star, bit harsh 😐
> 
> Honestly, the add-on does what it needs to do, so I haven't needed to update in years, though I personally still use daily (in Chrome though) - let me stoke the fox fire and give it a test. Generally closing and opening a new tabs makes it work again, but this seems to be a rare occurance.

Sorry for the 1 star, but I just wanted to (hope to) get your attention and I don't consider it bad at all! 😅

I have already removed the comment and I've to admit I didn't think this project was still alive lol.




> Just tested in Firefox and it worked ok, if you perform a restart using HA UI does it successfully complete?
> 
> ![image](https://user-images.githubusercontent.com/12653520/252880709-6a24cc0e-bb6f-4c82-a2ad-a313822387dd.png)

Hmm if it is working for you I wonder if the cause could be something else?

I actually cannot reboot Home Assistant (from Settings -> Three dots -> Restart Home Assistant)... it just doesn't restart.

The only way right now is by running `ha core restart` from SSH.

To confirm it is not a (Firefox) browser issue I tried to install the addon also for Chrome (I use no other addons for this browser) and it acts the same way:

I press the icon in the address bar to restart HA, it starts spinning forever and nothing happens.

In them meantime thanks for replying and let me know what you need to find out what's causing the issue. 😉

**Comment by warwickbuilds** [comment]
Yes it sounds like a bad config / .yaml file somewhere in your configuration, I would start by checking yaml config

Dev Tools > Yaml > Check Configuration

or in the logs

Settings > System > Logs

One of those should lead to what is going wrong, also hunt around for common restarting issues on the Home Assistant forums.

Once you get it restarting ok from the HA UI, this browser extension will also work fine.

👍 Good luck with it

**Comment by Cr4z33** [comment]
> Yes it sounds like a bad config / .yaml file somewhere in your configuration, I would start by checking yaml config
> 
> Dev Tools > Yaml > Check Configuration
> 
> or in the logs
> 
> Settings > System > Logs
> 
> One of those should lead to what is going wrong, also hunt around for common restarting issues on the Home Assistant forums.
> 
> Once you get it restarting ok from the HA UI, this browser extension will also work fine.
> 
> 👍 Good luck with it

Checking the configuration and then the logs was the key to find out a deprecated configuration entry.

As soon as I removed it and rebooted your addon is now perfectly working!

Thanks again for your help!
